DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS login_credentials CASCADE;


CREATE TABLE users (
    user_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar (40),
    first_name varchar (40),
    last_name varchar (40),
    summary text,
    linkedIn_link varchar(100),
    github_link varchar (100),
    profile_image text
);

CREATE TABLE projects (
    project_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_name varchar (40),
    project_link varchar (100),
    project_desc varchar (500),
    user_id int REFERENCES users ON DELETE CASCADE 
);

CREATE TABLE login_credentials (
    login_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar (50),
    password varchar (250)
);
