//get all users and passwords from login_credentials table
GET http://localhost:8000/users/credentials

###

//create new username and password to database
POST http://localhost:8000/user/create
Content-Type: application/json

{
    "username": "HaliBali",
    "password": "password"
}

###

//user login request to verify credentials and use for authorization
POST http://localhost:8000/user/login 
Content-Type: application/json

{
    "username": "HaliBali",
    "password": "password"
}
