//get all users and passwords from login_credentials table
GET http://localhost:8000/users/credentials

###

//create new username and password to database
POST http://localhost:8000/user/create
Content-Type: application/json

{
    "username": "joseph.t.low@gmail.com",
    "password": "password"
}

###

//user login request to verify credentials and use for authorization
POST http://localhost:8000/user/login 
Content-Type: application/json

{
    "username": "joseph.t.low@gmail.com",
    "password": "password"
}

### 
//request on API server to for authorization of user

GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9lIiwiaWF0IjoxNjY4NTQxNTEzLCJleHAiOjE2Njg1NDE1Mjh9.pkTyrIsKdYFrz4EvXPeTPg9FaqJykMwmgoGpicuwcw4


### 
//